theme: jekyll-theme-minimal
title: Nekotina
description: Una bot de discord de entretenimiento.
logo: https://cdn.discordapp.com/attachments/755529601333067940/779165856835698709/nekonekoneko.jpg
patreon_url: https://patreon.com/nekotina
support_url: https://discord.com/invite/nekotina
